# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Ramblin' Reck Club
email: technology@reckclub.org
description: > # this means to ignore newlines until "baseurl:"
  The history of the Ramblin' Reck
baseurl: "/reckhistory" # the subpath of your site, e.g. /blog
url: "https://ramblinreckclub.github.io" # the base hostname & protocol for your site
enforce_ssl: www.ramblinreckclub.github.io   # without any protocol

# Build settings
markdown: kramdown
